skills_list = [
    "python",
    "java",
    "c++",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "sql",
    "data science",
    "nlp",
    "computer vision",
    "docker",
    "kubernetes",
    "aws",
    "fastapi",
    "pandas",
    "numpy",
    "scikit-learn",
    "spark",
    "langchain",
    "hugging face",
    "mlflow"
]